export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "samiadoe",
			profileImg: "/avatars/boy1.png",
			fullName: "samia Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "farehdoe",
					profileImg: "/avatars/girl1.png",
					fullName: "fareh Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "saradoe",
			profileImg: "/avatars/boy2.png",
			fullName: "sara Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "ghaithdoe",
					profileImg: "/avatars/girl2.png",
					fullName: "ghaith Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "saradoe",
			profileImg: "/avatars/boy3.png",
			fullName: "sara Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "ayadoe",
			profileImg: "/avatars/boy3.png",
			fullName: "aya Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "sabahdoe",
					profileImg: "/avatars/girl3.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "sabah Doe",
		username: "sabahdoe",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "aya Doe",
		username: "ayadoe",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "chama Doe",
		username: "chamadoe",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "4",
		fullName: "chaimae",
		username: "chaimae",
		profileImg: "/avatars/girl2.png",
	},
];